escreva = input('Escreva algo: ')
print('Qual tipo primitivo foi digitado? {}'.format(type(escreva)))
print('Só tem espaços vazios? {}'.format(escreva.isspace()))
print('O que foi digitado é um número? {}'.format(escreva.isnumeric()))
print('Ele é alfabético? {}'.format(escreva.isalpha()))
print('É alfanumérico? {} '.format(escreva.isalnum()))
print('Tá digitado em maiúsculo? {}'.format(escreva.isupper()))
print('Tá tudo em minúsculo? {} '.format(escreva.islower()))
print('foi digitado de forma capitalizada? {}'.format(escreva.istitle()))